name = "urban-swing-spotify"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare Dashboard)
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET
# FIREBASE_PROJECT_ID (your Firebase project ID)
# FIREBASE_API_KEY (from Firebase console)

# Alternatively, set them here for development (NOT recommended for production)
# [vars]
# SPOTIFY_CLIENT_ID = "your_client_id"
# SPOTIFY_CLIENT_SECRET = "your_client_secret"
# FIREBASE_PROJECT_ID = "directed-curve-447204-j4"
# FIREBASE_API_KEY = "your_firebase_api_key"
